namespace TONL.NET;

/// <summary>
/// Base class for TONL serializer contexts that provide type metadata for AOT-safe serialization.
/// </summary>
/// <remarks>
/// This class mirrors System.Text.Json's JsonSerializerContext pattern. Derived classes
/// are generated by the TONL source generator and provide type-specific serialization
/// metadata without requiring runtime reflection.
///
/// Example usage:
/// <code>
/// [TonlSourceGenerationOptions]
/// [TonlSerializable(typeof(User))]
/// public partial class AppTonlContext : TonlSerializerContext { }
///
/// // Serialize with context
/// var tonl = TonlSerializer.Serialize(user, AppTonlContext.Default.User);
///
/// // Deserialize with context
/// var user = TonlSerializer.Deserialize(tonl, AppTonlContext.Default.User);
/// </code>
/// </remarks>
public abstract class TonlSerializerContext : ITonlTypeInfoResolver
{
    /// <summary>
    /// Gets the options used by this context.
    /// </summary>
    public TonlOptions? Options { get; }

    /// <summary>
    /// Initializes a new instance with default options.
    /// </summary>
    protected TonlSerializerContext()
        : this(null)
    {
    }

    /// <summary>
    /// Initializes a new instance with the specified options.
    /// </summary>
    /// <param name="options">The serialization options.</param>
    protected TonlSerializerContext(TonlOptions? options)
    {
        Options = options;
    }

    /// <summary>
    /// Gets the type info for the specified type.
    /// </summary>
    /// <param name="type">The type to get info for.</param>
    /// <returns>The type info, or null if not found.</returns>
    public abstract TonlTypeInfo? GetTypeInfo(Type type);

    /// <summary>
    /// Gets the type info for the specified type, throwing if not found.
    /// </summary>
    /// <typeparam name="T">The type to get info for.</typeparam>
    /// <returns>The type info.</returns>
    /// <exception cref="InvalidOperationException">The type is not registered in this context.</exception>
    public TonlTypeInfo<T> GetTypeInfo<T>()
    {
        var typeInfo = GetTypeInfo(typeof(T));
        if (typeInfo is not TonlTypeInfo<T> typedInfo)
        {
            throw new InvalidOperationException(
                $"Type '{typeof(T).FullName}' is not registered in this context. " +
                $"Add [TonlSerializable(typeof({typeof(T).Name}))] to your context class.");
        }

        return typedInfo;
    }
}
